### ISSUE TITLE
Segfault when iterator_new method called with schema as None

### ISSUE THREAD

**Issue by quintusdias** [python-xmp-toolkit/python-xmp-toolkit#28]
Differs from issue27 in that property is not None here, but it still may be the same case.

The test is test_no_namespace_single_prop_leaf_nodes.  The idea seems to be as to whether we can collect all leaf nodes for all schemas for a single property.  Does that even make sense?

**Comment by hfiguiere** [comment]
The segfault is that you don't check that the iterator is valid. You try to create an invalid iterator by passing the property name but "None" for the schema namespace, therefor you get a NULL iterator and never check for it. That can be fixed though.

**Comment by hfiguiere** [comment]
See PR #69
