### ISSUE TITLE
consts.XMP_PROP_OPTIONS does not match object_to_dict output

### ISSUE THREAD

**Issue by rschwiebert** [python-xmp-toolkit/python-xmp-toolkit#38]
After doing a conversion like object_to_dict or file_to_dict the complete list of options is:

array_is_alt
array_is_alttext
array_is_ordered
has_aliases
has_lang
has_qualifiers
has_type
is_alias
<b>is_derived</b>
is_internal
is_qualifier
is_schema
is_stable
value_is_array
value_is_struct
value_is_uri

The complete list of XMP_PROP_OPTIONS appears to be this:

prop_array_is_alt
prop_array_is_alttext
prop_array_is_ordered
<b>prop_array_is_unordered</b>
prop_has_aliases
prop_has_lang
prop_has_qualifiers
prop_has_type
prop_is_alias
<b>prop_is_deriver</b>
prop_is_internal
prop_is_qualifier
prop_is_schema
prop_is_stable
prop_value_is_array
prop_value_is_struct
prop_value_is_uri

It seems like "is_deriver" must be a typo, and I'm not sure if the prop_array_is_unordered is legitimate or not. Maybe it has been omitted from the *_to_dict operations, but it seems strange to have a property for *both* is_ordered and is_unordered...

**Comment by lnielsen** [comment]
Indeed ``prop_is_deriver`` looks to be a typo. The value is mapped to ``XMP_PROP_IS_DERIVED``.

``prop_array_is_unordered`` is ok. It's synonym with ``XMP_PROP_VALUE_IS_ARRAY``. This definition comes from the underlying C library Exempi.

**Comment by rschwiebert** [comment]
:+1: Cheers :)
