### ISSUE TITLE
Not saving updated files?

### ISSUE THREAD

**Issue by w2naf** [python-xmp-toolkit/python-xmp-toolkit#40]
Hi.  I'm trying to use your toolkit, but I can't get it to update the files, even after calling xmpfile.close().

I wrote a sample test which uses your BlueSquare sample files:

```
import libxmp
import libxmp.utils
from libxmp import XMPFiles, consts
from libxmp.utils import file_to_dict,object_to_dict

def print_obj(xmp):
    print 'PRINTING OBJECT'
    xmp_dict    = object_to_dict(xmp)
    dc          = xmp_dict[consts.XMP_NS_DC]
    for xx in dc:
        print xx[0],xx[1]

def print_file(fname):
    print 'PRINTING {}'.format(fname)
    xmp_dict    = file_to_dict(fname)
    dc          = xmp_dict[consts.XMP_NS_DC]
    for xx in dc:
        print xx[0],xx[1]

fnames  = ['BlueSquare.pdf','BlueSquare.png']

for fname in fnames:
    xmpfile = XMPFiles(file_path=fname,open_forupdate=True)
    xmp     = xmpfile.get_xmp()
    if xmp is None:
        xmp = libxmp.XMPMeta()

    xmp.set_property(consts.XMP_NS_DC,u'test_property',u'test_val')
    res = xmpfile.can_put_xmp(xmp)
    xmpfile.close_file()

    print_obj(xmp)
    print ''
    print_file(fname)
```

For both the PNG and PDF files, I can to the metadata, but cannot save to disk.  This is the result from print_obj() and print_file() above (PNG result, but PDF is essentially the same):

```
PRINTING OBJECT
dc:format application/vnd.adobe.photoshop
dc:title
dc:title[1] Blue Square Test File - .psd
dc:title[1]/?xml:lang x-default
dc:description
dc:description[1] XMPFiles BlueSquare test file, created in Photoshop CS2, saved as .psd, .jpg, and .tif.
dc:description[1]/?xml:lang x-default
dc:subject
dc:subject[1] XMP
dc:subject[2] Blue Square
dc:subject[3] test file
dc:subject[4] Photoshop
dc:subject[5] .psd
dc:test_property test_val

PRINTING BlueSquare.png
dc:format application/vnd.adobe.photoshop
dc:title
dc:title[1] Blue Square Test File - .psd
dc:title[1]/?xml:lang x-default
dc:description
dc:description[1] XMPFiles BlueSquare test file, created in Photoshop CS2, saved as .psd, .jpg, and .tif.
dc:description[1]/?xml:lang x-default
dc:subject
dc:subject[1] XMP
dc:subject[2] Blue Square
dc:subject[3] test file
dc:subject[4] Photoshop
dc:subject[5] .psd
```

Thanks for any help you can give,
Nathaniel

**Comment by quintusdias** [comment]
Hi Nathaniel, you are missing one line of code.  Change

    xmp.set_property(consts.XMP_NS_DC,u'test_property',u'test_val')
    res = xmpfile.can_put_xmp(xmp)
    xmpfile.close_file()


to

    xmp.set_property(consts.XMP_NS_DC,u'test_property',u'test_val')
    res = xmpfile.can_put_xmp(xmp)

    xmpfile.put_xmp(xmp)

    xmpfile.close_file()


You should then see the new attribute in the output.



On Mon, Jul 27, 2015 at 7:25 PM, Nathaniel Frissell <
notifications@github.com> wrote:

> Hi. I'm trying to use your toolkit, but I can't get it to update the
> files, even after calling xmpfile.close().
>
> I wrote a sample test which uses your BlueSquare sample files:
>
> import libxmp
> import libxmp.utils
> from libxmp import XMPFiles, consts
> from libxmp.utils import file_to_dict,object_to_dict
>
> def print_obj(xmp):
>     print 'PRINTING OBJECT'
>     xmp_dict    = object_to_dict(xmp)
>     dc          = xmp_dict[consts.XMP_NS_DC]
>     for xx in dc:
>         print xx[0],xx[1]
>
> def print_file(fname):
>     print 'PRINTING {}'.format(fname)
>     xmp_dict    = file_to_dict(fname)
>     dc          = xmp_dict[consts.XMP_NS_DC]
>     for xx in dc:
>         print xx[0],xx[1]
>
> fnames  = ['BlueSquare.pdf','BlueSquare.png']
>
> for fname in fnames:
>     xmpfile = XMPFiles(file_path=fname,open_forupdate=True)
>     xmp     = xmpfile.get_xmp()
>     if xmp is None:
>         xmp = libxmp.XMPMeta()
>
>     xmp.set_property(consts.XMP_NS_DC,u'test_property',u'test_val')
>     res = xmpfile.can_put_xmp(xmp)
>     xmpfile.close_file()
>
>     print_obj(xmp)
>     print ''
>     print_file(fname)
>
> For both the PNG and PDF files, I can to the metadata, but cannot save to
> disk. This is the result from print_obj() and print_file() above (PNG
> result, but PDF is essentially the same):
>
> PRINTING OBJECT
> dc:format application/vnd.adobe.photoshop
> dc:title
> dc:title[1] Blue Square Test File - .psd
> dc:title[1]/?xml:lang x-default
> dc:description
> dc:description[1] XMPFiles BlueSquare test file, created in Photoshop CS2, saved as .psd, .jpg, and .tif.
> dc:description[1]/?xml:lang x-default
> dc:subject
> dc:subject[1] XMP
> dc:subject[2] Blue Square
> dc:subject[3] test file
> dc:subject[4] Photoshop
> dc:subject[5] .psd
> dc:test_property test_val
>
> PRINTING BlueSquare.png
> dc:format application/vnd.adobe.photoshop
> dc:title
> dc:title[1] Blue Square Test File - .psd
> dc:title[1]/?xml:lang x-default
> dc:description
> dc:description[1] XMPFiles BlueSquare test file, created in Photoshop CS2, saved as .psd, .jpg, and .tif.
> dc:description[1]/?xml:lang x-default
> dc:subject
> dc:subject[1] XMP
> dc:subject[2] Blue Square
> dc:subject[3] test file
> dc:subject[4] Photoshop
> dc:subject[5] .psd
>
> Thanks for any help you can give,
> Nathaniel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python-xmp-toolkit/python-xmp-toolkit/issues/40>.
>



-- 
John Evans

**Comment by w2naf** [comment]
Hi, John.  Thank you; that fixed it!  That line is missing from the documentation.

One more question... I am trying to use this to add metadata to matplotlib-generated pdf and png files that do not already have xmp data.  I have not yet tested the PNG version, but at least for PDF I am doing this:

```
        import libxmp
        import libxmp.utils
        from libxmp import XMPFiles, consts
        xmpfile = XMPFiles(file_path=full_fname,open_forupdate=True)
        xmp     = xmpfile.get_xmp()
        if xmp is None:
            xmp = libxmp.XMPMeta()

        xmp.set_property(consts.XMP_NS_DC,u'generating_code',u'hello')
        res_0   = xmpfile.can_put_xmp(xmp)
        res_1   = xmpfile.put_xmp(xmp)
```
Here, res_0 turns out to be False.  The `res_1   = xmpfile.put_xmp(xmp)` statement results in an error:
```
XMPFiles::PutXMP - Can't inject XMP
Traceback (most recent call last):
  File "./north_america_mstid_map.py", line 312, in <module>
    main(map_time)
  File "./north_america_mstid_map.py", line 276, in main
    res_1   = xmpfile.put_xmp(xmp)
  File "/usr/local/lib/python2.7/dist-packages/libxmp/files.py", line 154, in put_xmp
    _cexempi.files_put_xmp( self.xmpfileptr, xmpptr )
  File "/usr/local/lib/python2.7/dist-packages/libxmp/exempi.py", line 516, in files_put_xmp
    EXEMPI.xmp_files_put_xmp(xfptr, xmp)
  File "/usr/local/lib/python2.7/dist-packages/libxmp/exempi.py", line 1702, in check_error
    raise XMPError(msg)
libxmp.XMPError: Exempi function failure ("unavailable").
```

Do you have a solution for this?

If so, I will be happy to update your documentation with a pull request.

Thanks!

~Nathaniel

**Comment by quintusdias** [comment]
Hi Nathaniel, PNG works, but I'm seeing the issue with PDF.  This seems
familiar somehow...  Will keep looking into this.

On Tue, Jul 28, 2015 at 10:19 PM, Nathaniel Frissell <
notifications@github.com> wrote:

> Hi, John. Thank you; that fixed it! That line is missing from the
> documentation.
>
> One more question... I am trying to use this to add metadata to
> matplotlib-generated pdf and png files that do not already have xmp data. I
> have not yet tested the PNG version, but at least for PDF I am doing this:
>
>         import libxmp
>         import libxmp.utils
>         from libxmp import XMPFiles, consts
>         xmpfile = XMPFiles(file_path=full_fname,open_forupdate=True)
>         xmp     = xmpfile.get_xmp()
>         if xmp is None:
>             xmp = libxmp.XMPMeta()
>
>         xmp.set_property(consts.XMP_NS_DC,u'generating_code',u'hello')
>         res_0   = xmpfile.can_put_xmp(xmp)
>         res_1   = xmpfile.put_xmp(xmp)
>
> Here, res_0 turns out to be False. The res_1 = xmpfile.put_xmp(xmp)
> statement results in an error:
>
> XMPFiles::PutXMP - Can't inject XMP
> Traceback (most recent call last):
>   File "./north_america_mstid_map.py", line 312, in <module>
>     main(map_time)
>   File "./north_america_mstid_map.py", line 276, in main
>     res_1   = xmpfile.put_xmp(xmp)
>   File "/usr/local/lib/python2.7/dist-packages/libxmp/files.py", line 154, in put_xmp
>     _cexempi.files_put_xmp( self.xmpfileptr, xmpptr )
>   File "/usr/local/lib/python2.7/dist-packages/libxmp/exempi.py", line 516, in files_put_xmp
>     EXEMPI.xmp_files_put_xmp(xfptr, xmp)
>   File "/usr/local/lib/python2.7/dist-packages/libxmp/exempi.py", line 1702, in check_error
>     raise XMPError(msg)
> libxmp.XMPError: Exempi function failure ("unavailable").
>
> Do you have a solution for this?
>
> If so, I will be happy to update your documentation with a pull request.
>
> Thanks!
>
> ~Nathaniel
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python-xmp-toolkit/python-xmp-toolkit/issues/40#issuecomment-125809984>
> .
>



-- 
John Evans

**Comment by w2naf** [comment]
Hi, John.  Thanks for looking into this!

~Nathaniel

**Comment by quintusdias** [comment]
Still looking at this... Going to be debugging the exempi library tonight with two separate PDF cases, trying to figure out why one case works and the other case doesn't.

**Comment by w2naf** [comment]
Thanks a lot!

~Nathaniel

**Comment by quintusdias** [comment]
So basically you can write XMP to PDF files that already have an XMP packet, but libexempi cannot write XMP into a PDF (or adobe illustrator, apparently) that does NOT already have an XMP packet.  So I guess that means you'd be limited to going with PNGs.

Sorry this took so long to get you an answer...  Turned out there was an issue filed about two years ago that was somewhat related to this, but also a 2nd that was exactly this issue, and I only remembered the first.  

This should be documented better, preferably in an error message that gives better information than 

```
XMPError: Exempi function failure ("unavailable").
```



See https://forums.adobe.com/thread/708717 for additional info.
