### ISSUE TITLE
Read XMP data from a BytesIO buffer (not a physical file)

### ISSUE THREAD

**Issue by sbaechler** [python-xmp-toolkit/python-xmp-toolkit#46]
I'd like to use the XMP Toolkit on a web server. The way the framework is set up the image storage is abstracted from the actual file. There might not even be a file at all. It is passed around the app as a `os.BytesIO` object.

Unfortunately the XMP Toolkit API only accepts file paths, and not file pointers. It looks like this is a limitation of the underlying Exempi library since all calls to the library pass the file name.

Is there maybe another way to use a BytesIO object or a Bytestring directly?

**Comment by quintusdias** [comment]
Hi Simon, it should be possible to do what you want, you just want to use the libxmp.XMPMeta object rather than libxmp.XMPFile.  The basic workflow would be

```
from libxmp import XMPMeta

xmp = XMPMeta()

# if b is your bytes object...
xmp.parse_from_str(b.decode('utf-8'))
```

Let me know if that gets you what you want.

**Comment by sbaechler** [comment]
Hi John

No, unfortunately this only works if you are passing it the extracted XML string. When you pass the whole image (and set `errors='ignore'` on the decode method) then XMP Toolkit fails with the message 

    *** XMPError: Exempi function failure ("bad XML").

This was with the "BlueSquare.jpg" test image from the XMP SDK.

It looks like the Adobe SDK supports reading from a buffer. It is even mentioned in the docs. The challenge is to convert a Python file pointer to a C file pointer.

**Comment by quintusdias** [comment]
Ok, I see what you are asking now.  I think that would be a limitation then
of the exempi library as it stands now.

Are these BytesIO objects representing JPEGs or TIFFs?

On Fri, Jan 8, 2016 at 9:47 AM, Simon Bächler <notifications@github.com>
wrote:

> Hi John
>
> No, unfortunately this only works if you are passing it the extracted XML
> string. When you pass the whole image (and set errors='ignore' on the
> decode method) then XMP Toolkit fails with the message
>
> *** XMPError: Exempi function failure ("bad XML").
>
> This was with the "BlueSquare.jpg" test image from the XMP SDK.
>
> It looks like the Adobe SDK supports reading from a buffer. It is even
> mentioned in the docs. The challenge is to convert a Python file pointer to
> a C file pointer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python-xmp-toolkit/python-xmp-toolkit/issues/46#issuecomment-170021784>
> .
>



-- 
John Evans

**Comment by sbaechler** [comment]
It can be anything. Usually Jpegs or PNGs. Basically the BytesIO buffer ist what you get from: 

    with open('BlueSquare.jpg', 'r') as f:
        buffer = f.read()
    file_like_obj = BytesIO(buffer)

To python it handles like a file except that there is no physical file. (On a web server, it could have been sent via a HTTP request)

I started implementing the extraction part in Python ([here](https://github.com/sbaechler/thumbor/blob/feature/metadata/thumbor/metadata/xmp_extractor.py)), but it gets complicated once the XMP file is split up into multiple parts because of the 64kb limitation. And of course there are different rules for every file type.

**Comment by RemiDesgrange** [comment]
I just posting a work around :

```python
from tempfile import NamedTemporaryFile
from libxmp import XMPFile

b=bytes() #  this is your image
with NamedTemporaryFile() as f:
    f.write(b)
    XMPFile(file_path=f.name)
```

**Comment by zougloub** [comment]
Closing as unsupported / please feel free to contribute support.
