### ISSUE TITLE
Feature Request: GUI/Nautilus scripts etc

### ISSUE THREAD

**Issue by Nichtraucher** [python-xmp-toolkit/python-xmp-toolkit#51]
Hey,

forgive me if I'm wrong here - I'm an end-user that desperately tries to find a friendly way to edit XMP Data.

I'm searching for a way to easily add/edit/remove keywords in certain files but I'm command-line challenged. A GUI is perhaps too much to ask for but maybe someone could create some simple scripts for file-managers (such as nautilus etc.) that allow such tasks on selected files/folders?

cheers

**Comment by lnielsen** [comment]
I think it's out of scope for this library - this is a Python library focused on providing programmers with the tools to programatically read/write XMP - i.e. if someone used Python to write a GUI program they could use the library to do the read/writing.

Besides that, many of Adobe's programs have nice editors for editing the XMP metadata - naturally you'll have to pay for them.

**Comment by Nichtraucher** [comment]
Yes, I expected that. By any chance, do you know of any software (preferably one for linux) that uses your toolkit to do just that - GUI-wise or not? I spend quite some time to find something that suits my needs and found nothing. :-(

**Comment by lnielsen** [comment]
I'm unfortunate not aware of any.
