### ISSUE TITLE
get_property leading to ambiguous Exempi failure

### ISSUE THREAD

**Issue by ostwind** [python-xmp-toolkit/python-xmp-toolkit#71]
Hi, I'm calling get_property() on a child node in the xmp of a tiff file. The namespace is RDF, and the actual node name is 'li', <rdf:li xml:lang="x-default"> . 

Exempi fails with an ambiguous message. Any insight? 

(also on a side note, what's the best way to edit the meta info of individual tiff pages? Make them individually then merge them together?) 

`Traceback (most recent call last):
  File "/home/lihan/Documents/image/src/preprocessing2.py", line 32, in <module>
    write_header()
  File "/home/lihan/Documents/image/src/preprocessing2.py", line 26, in write_header
    print(xmp.get_property(consts.XMP_NS_RDF, 'li') )
  File "/home/lihan/anaconda3/lib/python3.6/site-packages/libxmp/core.py", line 195, in get_property
    value, _ = _cexempi.get_property(self.xmpptr, schema_ns, prop_name)
  File "/home/lihan/anaconda3/lib/python3.6/site-packages/libxmp/exempi.py", line 670, in get_property
    _value, ctypes.byref(prop_bits))
  File "/home/lihan/anaconda3/lib/python3.6/site-packages/libxmp/exempi.py", line 1702, in check_error
    raise XMPError(msg)
libxmp.XMPError: Exempi function failure ("unknown error").`

**Comment by quintusdias** [comment]
Any chance you could post the tiff file so I could take a look?

**Comment by quintusdias** [comment]
Thanks for the file Lihan.  I actually cannot reproduce your issue, but...

I don't believe that the XMP toolkit is the best tool for what you want here.  The data you are trying to access is just regular XML embedded in a standard TIFF tag, so I would recommend using PIL with lxml instead, i.e.

from PIL import Image
from lxml import etree

im = Image.open(fname)
description = im.tag_v2[270]     # tag 270 is the Description
doc = etree.fromstring(description.encode('utf-16'))
etree.dump(doc)

After that, I might try xpath to extract individual items, e.g.

doc.xpath('.//AcquisitionSoftware/text()')

XPath does take a bit of getting used to...
