### ISSUE TITLE
Would you consider a PR for binary wheels?

### ISSUE THREAD

**Issue by jbarlow83** [python-xmp-toolkit/python-xmp-toolkit#75]
With a binary wheel one could eliminate the need to separately install libexempi3. This would simplify installation of python-xmp-toolkit down to simply `pip install python-xmp-toolkit`.

I'd be happy to do the work in a PR, which I've for several projects now. 

At the same time I'd update the version matrix to drop end of life versions and add the latest in the 3.x series.

However, since this project has been inactive for some time, I would appreciate if a contributor can confirm that they would be willing to consider such changes.

**Comment by lnielsen** [comment]
Sure, we're happy to integrate such a PR :-) Would be much appreciated.

**Comment by jbarlow83** [comment]
I did look into this but there's no standardized, non-hacky way to support ctypes accessing a library inside a binary wheel. It would be necessary to either create an extension module or switch to cffi binding (which builds an extension module under the hood). cffi would probably be the way to go.

Either way, this would be a bigger change than I am able to implement at the moment.
