### ISSUE TITLE
Release 2.0.2 does not exist

### ISSUE THREAD

**Issue by QuLogic** [python-xmp-toolkit/python-xmp-toolkit#80]
There is a PR #70 for it, but it was neither tagged nor uploaded to PyPI.

**Comment by thesamesam** [comment]
@quintusdias could you push the tag please and upload to pypi?

**Comment by zougloub** [comment]
Uploaded https://pypi.org/project/python-xmp-toolkit/2.0.2/, unfortunately the release was not uploadable to pypi, and I had to do an extra commit that landed in https://github.com/python-xmp-toolkit/python-xmp-toolkit/tree/2.0.2.x 

Expect a new release relatively soon.
